name: Awesome Checks
on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: curl

    - name: Run "Abandoned Check"
      run: php scripts/checkAbandoned.php
      env:
        GH_PA_TOKEN: ${{ secrets.GH_PA_TOKEN }}
